added more useful output in create-etcd-ca

diff --git a/bin/create-etcd-ca b/bin/create-etcd-ca
--- a/bin/create-etcd-ca
+++ b/bin/create-etcd-ca
@@ -24,4 +24,13 @@ echo '01' > ${ETCD_CA_DIR}/serial
 openssl req -config ${CLOUDCONFIG_INSTALL_DIR}/conf/openssl.cnf -new -x509 -extensions v3_ca \
   -keyout ${ETCD_CA_DIR}/private/${CN}.key -out ${ETCD_CA_DIR}/certs/${CN}.crt
 
-openssl x509 -in ${ETCD_CA_DIR}/certs/${CN}.crt -noout -text
+if [ $? -ne 0 ];then
+    echo "Could not create ca. Aborting!" 1>&2
+    exit 1
+fi
+
+echo
+echo Created certificate authority for CN=$CN
+echo Created private key in ${ETCD_CA_DIR}/private/${CN}.key
+echo Created certificate in ${ETCD_CA_DIR}/certs/${CN}.crt
+
